version: "3"
services: 
  ha:
    image: homeassistant/home-assistant:0.90.0
    ports:
      - 8123:8123
    volumes: 
      - ./configuration.yaml:/config/configuration.yaml
      - ./secrets.yaml:/config/secrets.yaml
      - ./custom_components:/config/custom_components